### ISSUE TITLE
ValueConnectableStream with asyncMap throws: 'pause' was called on null.

### ISSUE THREAD

**Issue by hpoul** [ReactiveX/rxdart#463]
Hi,
when using asyncMap on a (sync) ValueConnectableStream i am stumbling on an exception when a second listener subscribes. I *think* I am using the streams correctly. it looks like it is (kind of) working in 1.23 (at least no exception - did not test thoroughly yet), but throws in 1.24.1:

```dart
  final base = Stream.fromIterable(['']);
  final connectable = base
      .publishValue();
  connectable.connect();

  {
    final subscription = connectable.listen((event) {});
    await subscription.cancel();
  }
  {
    final subscription =
        connectable.asyncMap((event) async => event).listen((event) {});
    await subscription.cancel();
  }
```

You can see a running example in this repl: https://repl.it/@hpoul/rxdart-publishValue-with-asyncMap

<details>
  <summary>Exception:</summary>
<pre>
Unhandled exception:
NoSuchMethodError: The method 'pause' was called on null.
Receiver: null
Tried calling: pause()
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      Stream.asyncMap.onListen.<anonymous closure> (dart:async/stream.dart:520:24)
#2      _RootZone.runUnaryGuarded (dart:async/zone.dart:1374:10)
#3      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#4      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#5      _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:378:20)
#6      _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:252:5)
#7      _StartWithStreamSink._safeAddFirstEvent (package:rxdart/src/transformers/start_with.dart:56:12)
#8      _StartWithStreamSink.onListen (package:rxdart/src/transformers/start_with.dart:37:11)
#9      forwardStream.<anonymous closure>.<anonymous closure> (package:rxdart/src/utils/forwarding_stream.dart:31:37)
#10     forwardStream.runCatching (package:rxdart/src/utils/forwarding_stream.dart:24:12)
#11     forwardStream.<anonymous closure> (package:rxdart/src/utils/forwarding_stream.dart:31:16)
#12     _runGuarded (dart:async/stream_controller.dart:820:24)
#13     _BroadcastStreamController._subscribe (dart:async/broadcast_stream_controller.dart:215:7)
#14     _ControllerStream._createSubscription (dart:async/stream_controller.dart:833:19)
#15     _StreamImpl.listen (dart:async/stream_impl.dart:475:9)
#16     DeferStream.listen (package:rxdart/src/streams/defer.dart:37:18)
#17     StreamView.listen (dart:async/stream.dart:1849:20)
#18     StreamView.listen (dart:async/stream.dart:1849:20)
#19     Stream.asyncMap.onListen (dart:async/stream.dart:511:27)
#20     _runGuarded (dart:async/stream_controller.dart:820:24)
#21     _BroadcastStreamController._subscribe (dart:async/broadcast_stream_controller.dart:215:7)
#22     _ControllerStream._createSubscription (dart:async/stream_controller.dart:833:19)
#23     _StreamImpl.listen (dart:async/stream_impl.dart:475:9)
#24     main (file:///Users/herbert/dev/playground/dart-playground/bin/rxdart_playground3.dart:84:54)
#25     _RootZone.runUnary (dart:async/zone.dart:1439:54)
#26     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#27     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#28     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#29     Future._addListener.<anonymous closure> (dart:async/future_impl.dart:391:9)
#30     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#31     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#32     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#33     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
</pre>
</details>

When I use `ValueConnectableStream(base, sync: false);` instead of `base.publishValue` it seems to at least not throw.

Am i misusing the connectable stream, or should this work?

**Comment by frankpepermans** [comment]
There's an annoying issue inside the Dart Stream library where a Stream can throw when being subscribed to too early, 

I'll take a close look asap (we've predominantly encountered this with startWith for example)

**Comment by hoc081098** [comment]
Same
```dart
await BehaviorSubject<int>.seeded(2).first;
```
IMO, It is caused by `Stream` is **sync Stream**

**Comment by frankpepermans** [comment]
https://github.com/dart-lang/sdk/issues/41969

**Comment by hpoul** [comment]
thanks for investigating :) I'm just happy that i'm not misusing something, and it seems when using an async stream, everything works, so easy workaround i guess..

**Comment by nl-brett-stime** [comment]
Per https://github.com/dart-lang/sdk/issues/41969#issuecomment-633859807, it sounds like rxdart might be calling the add method on the stream controller (or otherwise mutating the upstream) from a listener somewhere.

**Comment by nl-brett-stime** [comment]
...from my stack trace, it looks like it might be in `_StartWithStreamSink.onListen`:

```
E/flutter ( 2816): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The method 'pause' was called on null.
E/flutter ( 2816): Receiver: null
E/flutter ( 2816): Tried calling: pause()
E/flutter ( 2816): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
E/flutter ( 2816): #1      Stream.asyncMap.onListen.<anonymous closure> (dart:async/stream.dart:520:24)
E/flutter ( 2816): #2      _rootRunUnary (dart:async/zone.dart:1192:38)
E/flutter ( 2816): #3      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter ( 2816): #4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
E/flutter ( 2816): #5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter ( 2816): #6      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
E/flutter ( 2816): #7      _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:378:20)
E/flutter ( 2816): #8      _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:252:5)
E/flutter ( 2816): #9      _StartWithStreamSink._safeAddFirstEvent (package:rxdart/src/transformers/start_with.dart:56:12)
E/flutter ( 2816): #10     _StartWithStreamSink.onListen (package:rxdart/src/transformers/start_with.dart:37:11)
...
```

**Comment by frankpepermans** [comment]
should be resolved with 0.25.0-beta
