### ISSUE TITLE
Runtime crash after updating from 0.23.1 to 0.24.0 and 0.24.1

### ISSUE THREAD

**Issue by robindijkhof** [ReactiveX/rxdart#475]
After updating to 0.24.0 and 0.24.1 I got some crashes. Here is the stacktrace.

**E/flutter ( 5580): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The method '[]' was called on null.
E/flutter ( 5580): Receiver: null
E/flutter ( 5580): Tried calling: [](2)
E/flutter ( 5580): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
E/flutter ( 5580): #1      ZipStream._buildController.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:rxdart/src/streams/zip.dart:318:57)
E/flutter ( 5580): #2      _rootRunUnary (dart:async/zone.dart:1192:38)
E/flutter ( 5580): #3      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter ( 5580): #4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
E/flutter ( 5580): #5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter ( 5580): #6      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
E/flutter ( 5580): #7      _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:134:11)
E/flutter ( 5580): #8      _TakeStream._handleData (dart:async/stream_pipe.dart:328:12)
E/flutter ( 5580): #9      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:166:13)
E/flutter ( 5580): #10     _rootRunUnary (dart:async/zone.dart:1192:38)
E/flutter ( 5580): #11     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter ( 5580): #12     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
E/flutter ( 5580): #13     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter ( 5580): #14     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
E/flutter ( 5580): #15     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:378:20)
E/flutter ( 5580): #16     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:252:5)
E/flutter ( 5580): #17     _StartWithStreamSink._safeAddFirstEvent (package:rxdart/src/transformers/start_with.dart:56:12)
E/flutter ( 5580): #18     _StartWithStreamSink.onListen (package:rxdart/src/transformers/start_with.dart:37:11)
E/flutter ( 5580): #19     forwardStream.<anonymous closure>.<anonymous closure> (package:rxdart/src/utils/forwarding_stream.dart:31:37)
E/flutter ( 5580): #20     forwardStream.runCatching (package:rxdart/src/utils/forwarding_stream.dart:24:12)
E/flutter ( 5580): #21     forwardStream.<anonymous closure> (package:rxdart/src/utils/forwarding_stream.dart:31:16)
E/flutter ( 5580): #22     _runGuarded (dart:async/stream_controller.dart:820:24)
E/flutter ( 5580): #23     _BroadcastStreamController._subscribe (dart:async/broadcast_stream_controller.dart:215:7)
E/flutter ( 5580): #24     _ControllerStream._createSubscription (dart:async/stream_controller.dart:833:19)
E/flutter ( 5580): #25     _StreamImpl.listen (dart:async/stream_impl.dart:475:9)
E/flutter ( 5580): #26     DeferStream.listen (package:rxdart/src/streams/defer.dart:37:18)
E/flutter ( 5580): #27     StreamView.listen (dart:async/stream.dart:1849:20)
E/flutter ( 5580): #28     new _ForwardingStreamSubscription (dart:async/stream_pipe.dart:125:10)
E/flutter ( 5580): #29     new _StateStreamSubscription (dart:async/stream_pipe.dart:351:9)
E/flutter ( 5580): #30     _TakeStream._createSubscription (dart:async/stream_pipe.dart:320:16)
E/flutter ( 5580): #31     _ForwardingStream.listen (dart:async/stream_pipe.dart:88:12)
E/flutter ( 5580): #32     ZipStream._buildController.<anonymous closure>.<anonymous closure> (package:rxdart/src/streams/zip.dart:326:43)
E/flutter ( 5580): #33     MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
E/flutter ( 5580): #34     ListIterable.toList (dart:_internal/iterable.dart:221:19)
E/flutter ( 5580): #35     ZipStream._buildController.<anonymous closure> (package:rxdart/src/streams/zip.dart:328:20)
E/flutter ( 5580): #36     _runGuarded (dart:async/stream_controller.dart:820:24)
E/flutter ( 5580): #37     _StreamController._subscribe.<anonymous closure> (dart:async/stream_controller.dart:699:7)
E/flutter ( 5580): #38     _BufferingStreamSubscription._guardCallback (dart:async/stream_impl.dart:417:13)
E/flutter ( 5580): #39     _StreamController._subscribe (dart:async/stream_controller.dart:698:18)
E/flutter ( 5580): #40     _ControllerStream._createSubscription (dart:async/stream_controller.dart:833:19)
E/flutter ( 5580): #41     _StreamImpl.listen (dart:async/stream_impl.dart:475:9)
E/flutter ( 5580): #42     StreamView.listen (dart:async/stream.dart:1849:20)
E/flutter ( 5580): #43     new _ForwardingStreamSubscription (dart:async/stream_pipe.dart:125:10)
E/flutter ( 5580): #44     new _StateStreamSubscription (dart:async/stream_pipe.dart:351:9)
E/flutter ( 5580): #45     _TakeStream._createSubscription (dart:async/stream_pipe.dart:320:16)
E/flutter ( 5580): #46     _ForwardingStream.listen (dart:async/stream_pipe.dart:88:12)
E/flutter ( 5580): #47     new _ForwardingStreamSubscription (dart:async/stream_pipe.dart:125:10)
E/flutter ( 5580): #48     _ForwardingStream._createSubscription (dart:asyn**

I have been trying to pinpoint this issue for days but I am still not sure what is the root cause. It has something to do with `zipList` and `problemStream`.

    List<Stream> streams = [
      $someStream1.take(1),
      $someStream2.take(1),
      $someStream3.take(1),
      $problemStream.take(1)
    ].map(//doStuff).listen(//doStuff);

The above example results in the error. It does not reach the `listen` or the `map`. When removing `$problemStream` there is no error. Listening directly to the `$problemStream` also causes no error.

    final ReplayStream<List<Job>> $problemStream = getDatabaseHelper().getJobs().map((list) {
      List<Job> newList = List();
      newList.add(Job('All'.i18n));
      newList.addAll(list);
      return newList;
    }).shareReplay(maxSize: 1);

`getJobs()`:

    Stream<List<Job>> getJobs() {
      return _getJobsRef().asStream()
          .switchMap((ref) => ref.orderByChild('order').onValue)
          .map((event) =>
              event.snapshot.value != null ? SnapshotMapper.jobListFromSnapshot(event.snapshot.value) : List<Job>())
          .distinct((a, b) => const IterableEquality().equals(a, b))
          .shareReplay(maxSize: 1);
    }

`_getJobsRef()` is a `Future` with a [Firebase Database Ref](https://pub.dev/packages/firebase_database/example). `ref.orderByChild('order').onValue` is a `Stream` with the data from the database.

I am pretty clueless because it was working on 0.23.1. I did not see any changes that could explain my problem. Also, my code is not that complex. I tried recreating a small example but I can not figure out what is actually causing the issue. Any ideas?

**Comment by hoc081098** [comment]
Seems error thrown from `zipper` function

**Comment by frankpepermans** [comment]
It's not the zipper, 
in our zip implementation, we build a `List` of `StreamSubscription` and as soon as an event is emitted, we pause the corresponding `StreamSubscription`.

But, the event fires immediately after `onListen`, at this point our subscriptions `List` is still null.

The error corresponds to this line: https://github.com/ReactiveX/rxdart/blob/master/lib/src/streams/zip.dart#L324

**Comment by frankpepermans** [comment]
@robindijkhof It seems that the `problemStream` is a `sync` `Stream`, any chance you could make it an `async` one?

**Comment by robindijkhof** [comment]
I'm not familiar with the term `(a)sync stream`. Mind sharing an example or explaining?

**Comment by frankpepermans** [comment]
Never mind, was just following the stack trace you posted,
Any chance you can provide a reproducible piece of code?

**Comment by robindijkhof** [comment]
Already tried a few hours doing so. Maybe I'm more lucky tomorrow. Would it be a problem if it was in flutter with firebase?

**Comment by frankpepermans** [comment]
Same here, can't seems to reproduce with simple tests,

Flutter + fb is okay for me

**Comment by robindijkhof** [comment]
@frankpepermans I created an example. https://github.com/robindijkhof/crashtest.
It would require you to set setup an example project. You can also send met you SHA1 and SHA256 debug key fingerprints

**Comment by frankpepermans** [comment]
Hey, mind giving 0.25.0-beta a go?

**Comment by robindijkhof** [comment]
@frankpepermans a bit late, but `0.25.0-beta` seems to be working.
